Add automatic zone generation based on exploration condition
kuroppoi/brainwine pull request #44
Opened 2024-04-21 22:10 UTC by boraini

The game will create world with a random biome if all the current worlds are explored beyond 40%.

Technical questions:
 - [ ] I am not sure about the polling code I have implemented. It uses counters and flags which make the feature stateful. Maybe review it and tell me if there is a better way to run code every 20 seconds or so.

2024-04-22 22:50 UTC, kuroppoi requested changes

2024-04-22 22:50 UTC, kuroppoi commented on gameserver/src/main/java/brainwine/gameserver/zone/ZoneManager.java
> +    int generateZoneAttemptCounter = 0;
Fields have default visibility; please explicitly declare them to be `private`.

2024-04-22 22:50 UTC, kuroppoi commented on gameserver/src/main/java/brainwine/gameserver/zone/ZoneManager.java
> +        if (++generateZoneAttemptCounter == 20) {
The gameserver runs at 8 ticks per second (in ideal circumstances)
 so this code will run every 2.5 seconds rather than 20.
It might also be more appropriate to use [system time](https://github.com/kuroppoi/brainwine/blob/master/gameserver/src/main/java/brainwine/gameserver/zone/Zone.java#L140) instead.

2024-04-22 22:50 UTC, kuroppoi commented on gameserver/src/main/java/brainwine/gameserver/zone/ZoneManager.java
> +                generator.generateZoneAsync(biome, width, height, seed, zone -> {
`generateZoneAsync` may pass `null` if an exception is thrown, so it should check for that before calling `addZone`.
I'm sorry that it isn't documented anywhere! 🤣

2024-04-23 14:52 UTC, kuroppoi requested changes

2024-04-23 14:52 UTC, kuroppoi commented on gameserver/src/main/java/brainwine/gameserver/zone/ZoneManager.java
> +    boolean generatingZone = false;
Fields have default visibility; please explicitly declare them to be private.

2024-04-23 14:52 UTC, kuroppoi commented on gameserver/src/main/java/brainwine/gameserver/zone/ZoneManager.java
> +        }
The gameserver runs at 8 ticks per second (in ideal circumstances)
so this code will run every 2.5 seconds rather than 20.
It might also be more appropriate to use [system time](https://github.com/kuroppoi/brainwine/blob/master/gameserver/src/main/java/brainwine/gameserver/zone/Zone.java#L140) instead.

2024-04-23 14:52 UTC, kuroppoi commented on gameserver/src/main/java/brainwine/gameserver/zone/ZoneManager.java
> +                });
`generateZoneAsync` may pass `null` if an exception is thrown during zone generation,
so it should check for that before calling `addZone`. I'm sorry that this isn't documented anywhere! 🤣

2024-04-23 14:54 UTC, kuroppoi commented on gameserver/src/main/java/brainwine/gameserver/zone/ZoneManager.java
> +    }
This is fine for now but should be updated to filter out player-owned worlds in the future.

2024-04-23 16:45 UTC, boraini commented on gameserver/src/main/java/brainwine/gameserver/zone/ZoneManager.java
> +    }
Alright. I will look into these some time this evening. I had been busy yesterday. Please don't hesitate commenting on more stuff if you wish to.

2024-05-01 20:36 UTC, kuroppoi requested changes

2024-05-01 20:36 UTC, kuroppoi commented on gameserver/src/main/java/brainwine/gameserver/zone/ZoneManager.java
> +        }
This block of code will only run every two hours regardless of player count because of the check at line 85,
which makes the additional check for `requiredInterval` rather pointless.
You can probably just remove the check at line 85 and it'll work fine.

2024-05-01 20:36 UTC, kuroppoi commented on gameserver/src/main/java/brainwine/gameserver/zone/ZoneManager.java
> +                    generator.generateZoneAsync(biome, width, height, seed, zone -> {
[generateZoneAsync(biome, callback)](https://github.com/kuroppoi/brainwine/blob/develop/gameserver/src/main/java/brainwine/gameserver/zone/gen/ZoneGenerator.java#L168) will automatically generate a width, height and seed, so you can omit those here.

2024-05-01 20:36 UTC, kuroppoi commented on gameserver/src/main/java/brainwine/gameserver/zone/ZoneManager.java
> +        timeSinceLastGeneration += deltaTime;
This is optional but I recommend using system time for this rather than delta time.

Example:
https://github.com/kuroppoi/brainwine/blob/1eda98539c6f65565d00aacbd5b186a836e47f1d/gameserver/src/main/java/brainwine/gameserver/GameServer.java#L86-L90

2024-05-01 21:20 UTC, boraini commented on gameserver/src/main/java/brainwine/gameserver/zone/ZoneManager.java
> +        }
Yeah there is a bug. It should have been `> MIN_GENERATION_INTERVAL_SECONDS` please confirm that this would fix the problem according to you.

2024-05-01 21:25 UTC, kuroppoi commented on gameserver/src/main/java/brainwine/gameserver/zone/ZoneManager.java
> +        }
Yes that looks like it would fix it.
Makes the extra check for `generatingZone` at line 91 redundant, though.

2024-05-02 20:39 UTC, kuroppoi commented on gameserver/src/main/java/brainwine/gameserver/zone/ZoneManager.java
> +    private float lastZoneGenerationTime = System.currentTimeMillis();
Doesn't work -- this should be a `long` instead of a `float`.

2024-05-05 22:59 UTC, boraini commented
I also tested it with the new build system, and even if I don't do it for this PR, I will use the new build system for my further work.

2024-05-06 19:59 UTC, merged

2024-05-06 20:15 UTC, kuroppoi commented
Works great, thanks!