Conveyor belt using behavior tree
kuroppoi/brainwine pull request #55
Opened 2024-05-23 02:39 UTC by boraini

Change WalkBehavior so it checks if the NPC is on top of an item with an use type of move: true, and behave differently in that case.
- [ ] The entities might be going too fast.

2024-05-23 11:22 UTC, kuroppoi requested changes

2024-05-23 11:22 UTC, kuroppoi commented on gameserver/src/main/java/brainwine/gameserver/entity/npc/behavior/parts/WalkBehavior.java
> +        if (zone != null) {
Check is redundant: `zone` will never be `null` in this location.

2024-05-23 11:22 UTC, kuroppoi commented on gameserver/src/main/java/brainwine/gameserver/zone/Zone.java
> +
I'd rather have this function moved to the `WalkBehavior` or `Npc` class and have it serve as a function to find the block the entity is standing on.

2024-05-23 11:22 UTC, kuroppoi commented on gameserver/src/main/java/brainwine/gameserver/entity/npc/behavior/parts/WalkBehavior.java
> +        }
The `setAnimation` calls here will change the _behavior's_ animation, which should not be done.
Use `entity.setAnimation(name)`,`entity.move(x, y, animation)` or `entity.move(x, y, speed, animation)` to update the NPC's animation.

2024-05-23 11:22 UTC, kuroppoi commented on gameserver/src/main/java/brainwine/gameserver/entity/npc/behavior/parts/WalkBehavior.java
> +            entity.move(movingSurfacePower.intValue(), 0, animation);
`movingSurfacePower` should probably be used as the NPC's speed rather than its movement offset.
Speed can be updated using `entity.setSpeed(speed)`, but using `entity.move(x, y, speed, animation)` to set everything in one go is preferred.

2024-05-23 11:22 UTC, kuroppoi commented on gameserver/src/main/java/brainwine/gameserver/entity/npc/behavior/parts/WalkBehavior.java
> +        Float movingSurfacePower = null;
Non-primitive numbers are scary. I suggest simply checking if `block` is `null` instead.

2024-05-24 16:15 UTC, boraini commented on gameserver/src/main/java/brainwine/gameserver/zone/Zone.java
> +
I agree with all the other comments but what is wrong with having the findBlock function here? I think it is relevant on the zone domain, and could be used to refactor a lot more logic in the future since testing for large blocks occupying a block position is important. Also, could I do something with metablocks instead (I don't think so at all)?

2024-05-24 17:00 UTC, kuroppoi commented on gameserver/src/main/java/brainwine/gameserver/zone/Zone.java
> +
It's fine to keep it there, but then I would suggest updating `isBlockSolid(x, y, checkAdjacents)` to use this function in order to keep duplicate code to a minimum.

Edit: To answer your second question, conveyor belts aren't metablocks, so no.
It's not really appropriate to query metablocks in a scenario such as this, anyway.
Metablocks typically exist for one of two reasons:
- To store extra data (loot containers, player-configurable signs, etc.)
- To quickly find the location(s) of important blocks without loading chunks (zone teleporters, protectors, etc.)

Storing metablocks can be rather expensive because of this, so I would advise against turning items into metablocks without a good reason.

2024-05-24 20:35 UTC, boraini commented on gameserver/src/main/java/brainwine/gameserver/zone/Zone.java
> +
So my suspicion about metablocks being similar to tile entities from Minecraft was correct. I will keep this in mind. Also, I will refactor isBlockSolid. I have thought about it but wouldn't change it before asking.

2024-05-24 23:12 UTC, boraini commented on gameserver/src/main/java/brainwine/gameserver/zone/Zone.java
> +
Hi. Can you please check https://github.com/boraini/brainwine/pull/7 before I add it here?

2024-05-25 13:52 UTC, kuroppoi commented on gameserver/src/main/java/brainwine/gameserver/zone/Zone.java
> +
Yeah looks good, feel free to include it here. I'll edit the nitpicky things myself later.

2024-05-25 14:16 UTC, boraini commented
Another thing... Do we want the NPCs to look towards west and east randomly while going on the conveyors? It seems to be the case in the Ruby server.

2024-05-25 16:26 UTC, kuroppoi commented
There seems to be a bug regarding this, actually.
Apparently, conveyor belts give entities the special ability to walk through solid walls.

2024-05-28 15:53 UTC, kuroppoi commented
I took the liberty of changing a few nitpicky things, but the bug remains.
It seems to happen because the conveyor belt can move entities in directions that they aren't facing, which bypasses the solid wall check.
An easy solution would be to implement an additional solid wall check before the conveyor belt movement section.

2024-05-28 17:55 UTC, boraini commented
> I took the liberty of changing a few nitpicky things, but the bug remains. It seems to happen because the conveyor belt can move entities in directions that they aren't facing, which bypasses the solid wall check. An easy solution would be to implement an additional solid wall check in the conveyor belt movement section.

I was afraid of introducing bugs so I didn't do much code shortening myself. I will look into clipping into the walls today since I am done with university stuff.

2024-05-28 19:57 UTC, boraini commented
Hello. I have added a fix for the wall clipping problem. I also changed the architecture of the conveyor belt behavior so it can be composed into other behavior types easily. You can see the work for that in https://github.com/boraini/brainwine/pull/8. Tell me if you want it.

2024-05-28 20:48 UTC, kuroppoi commented
Probably a better idea yeah, feel free to include it.

2024-05-28 20:55 UTC, boraini commented on gameserver/src/main/java/brainwine/gameserver/entity/npc/behavior/Behavior.java
> +    @Type(name = "conveyor_belt", value = ConveyorBeltBehavior.class),
Make sure to check if this is fine please.

2024-05-28 21:48 UTC, kuroppoi commented on gameserver/src/main/java/brainwine/gameserver/entity/Entity.java
> +
Utility function

2024-05-28 21:48 UTC, kuroppoi commented on gameserver/src/main/java/brainwine/gameserver/entity/npc/Npc.java
> +
More utility

2024-05-28 21:48 UTC, kuroppoi commented on gameserver/src/main/java/brainwine/gameserver/entity/npc/behavior/composed/WalkerBehavior.java
> +
Conveyor behavior should always go first because idle behavior can cancel out the movement

2024-05-28 21:50 UTC, kuroppoi commented on gameserver/src/main/java/brainwine/gameserver/entity/npc/behavior/parts/ConveyorBehavior.java
> +    }
I removed the `@JsonAlias` annotation since it's only there for out-of-the-box compatibility with the game configuration (conveyor behavior isn't standard so it is not necessary)

2024-05-28 21:51 UTC, kuroppoi commented on gameserver/src/main/java/brainwine/gameserver/entity/npc/behavior/parts/ConveyorBehavior.java
> +        return conveyorBlock != null;
Behavior is instanced so we can grab the conveyor block here and save it instead of doing it twice

2024-05-28 21:52 UTC, kuroppoi commented on gameserver/src/main/java/brainwine/gameserver/entity/npc/behavior/parts/ConveyorBehavior.java
> +        }
Not really fond of this one myself but it does the job well enough I'd say

2024-05-28 23:31 UTC, merged